### ISSUE TITLE
AdAway doesn't work on Android 4.4

### ISSUE THREAD

**Issue by ckuethe** [sufficientlysecure/ad-away#476]
Similar to  http://forum.xda-developers.com/showthread.php?p=47049765

AdAway has been spinning for 10 minutes at the "Applying..." stage. There are no log entries to indicate what's going on.

Even after rebooting and manually installing a hosts file, I'm still able to resolve unwanted hosts.

```
root@hammerhead:/sdcard # grep m.doubleclick.com /etc/hosts                    
127.0.0.1 m.doubleclick.com
root@hammerhead:/sdcard # ls -l /etc/hosts                                     
lrwxrwxrwx root     root              2013-11-04 16:58 hosts -> /data/data/hosts
root@hammerhead:/sdcard # ls -l /data/data/hosts                               
-rw-r--r-- root     root       881709 2013-11-04 16:58 hosts
root@hammerhead:/sdcard # grep m.doubleclick.com /etc/hosts                    
127.0.0.1 m.doubleclick.com
root@hammerhead:/sdcard # ping m.doubleclick.com                               
PING s0-2mdn-net.l.google.com (74.125.239.156) 56(84) bytes of data.
64 bytes from nuq05s02-in-f28.1e100.net (74.125.239.156): icmp_seq=1 ttl=54 time=4.66 ms
64 bytes from nuq05s02-in-f28.1e100.net (74.125.239.156): icmp_seq=2 ttl=54 time=17.8 ms
^C
--- s0-2mdn-net.l.google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 4.667/11.259/17.851/6.592 ms
```

**Comment by Arinerron** [comment]
Hate to bring this issue back from the grave, but it isn't working with Android Nougat stock ROM (Nexus 5x). 

Same problem as everyone here, the system just doesn't pay attention to the hosts file. USB Debugging/adb enabled, rooted, ANDROID_DNS_MODE=true, and gave 777 perms. 

I don't know what is going on, and I've tried several guides/posts. Can anyone help?

**Comment by PainterAndHacker** [comment]
I'm having the same issue as @Arinerron. I'm on CM 14.1 on the Nexus 5x, with Android 7.1.

I created a symlink from /system/etc/hosts -> /data/data/hosts, but pinging one of the entries in the host file resolves to its actual IP. If I export ANROID_DNS_MODE=local and then ping, it works. My browsers seem to be ignoring /system/etc/hosts as well.

Any idea what might be happening?

**Comment by GldRush98** [comment]
Whatever it is, your issue is a new issue.  This issue is about an issue specific to Android 4.4 and has been closed for over 3 years now.  Please stop posting comments to it as it emails all the people who commented in here 3 years ago including myself.  You should be opening a new issue specific the problem you're having on the version of Android you're running.  Stop bumping a closed unrelated issue.

**Comment by Arinerron** [comment]
@NathanColeman and @GldRush98 https://github.com/AdAway/AdAway/issues/830

**Comment by tungsteen1791** [comment]
Hello everyone, hello GldRush98 too. The issue consistently the same, it isn't new. It is October 13th, 2017 and I was able to resolve the real problem here, from this post. I wanted you and anyone looking for a fix that it is related to supersu as is mentioned above. 
Disable notification for AdAway within super user settings and it perfectly works. 

I was looking for this fix for many months as resolving this now makes my beloved gadget for business loved even more. Thank you very much.
