### ISSUE TITLE
Web server HTTPS support

### ISSUE THREAD

**Issue by Nick-White** [sufficientlysecure/ad-away#550]
Does the webserver work for HTTPS? Yahoo for example uses secure ads,
and I get a "website cannot be displayed" area instead of a white space and on Boat Browser an error messagebox that secure connection failed.

**Comment by 0-kaladin** [comment]
Can't really change that behavior because of the secure nature of HTTPS.

**Comment by Nick-White** [comment]
Could you explain a bit?

The ad images are from a different domain so it doesn't have to be the same certificate as Yahoo's. The blank server's can be self signed.

**Comment by 0-kaladin** [comment]
I'm not sure a self signed cert helps you.  chrome won't trust it for sure and i don't know how boat leverages a root store but probably won't trust it either.  so it still will be some sort of untrusted https session to the ad domain.  which will generally prompt some sort of error instead of the nice blank page you can get with the http requests.  I can try to add a self signed cert i just don't think we will gain anything.
