### ISSUE TITLE
Live Person Chat Got Falsely Entered in List

### ISSUE THREAD

**Issue by ehostlab** [sufficientlysecure/ad-away#563]
Hi,

Live Person (http://www.liveperson.com/) Provides Live Chat for Websites. But, when I use AdAway Application to remove the Ads, it also vanishes Live Person's Live Chat. Their Live Chat links start like this:

https://server.iad.liveperson.net/hc/84421077/?cmd=file&file=visitorWantsToChat&site=84421077&SESSIONVAR!skill=sales-english

Neither their Main Website opens nor their Live Chat opens while I run AdAway to modify Host File & when I disable this, I can chat without any issue.

**Comment by TameOfGroans** [comment]
what have YOU added to WhiteList to remedy this yourself?

WhiteList is an app feature to not-block hosts of YOU choosing. AdAway allows YOU to subscribe to various lists. With zero lists [no subscription, and no BlackList] Adaway will block nothing.

Since you have root you might also want to try UnbelovedHosts -- but not until you grasp both the subscription list- and BlackList/WhiteList notions. 

To protect yourself from deceitful app developers also similarly consider MinMinGuard.  I'm moral developers are failing to obtain Informed Consent for their Malware Payment Extraction by User Injury ideology.

**Comment by TameOfGroans** [comment]
LogDNSrequests will help you yourself identify what is being blocked. View log, long click hosts to WhiteList.

easy.

check for updates to integrate new BlackList entries. 

for other questions of use:

https://github.com/dschuermann/ad-away/wiki/
