### ISSUE TITLE
Adaway blocks ARD Mediathek in Firefox

### ISSUE THREAD

**Issue by kakaduh** [sufficientlysecure/ad-away#578]
Hello,

it seems like a filter lists Adaway uses at the moment blocks videos on http://www.ardmediathek.de/tv when watched in a browser (e. g. Firefox). The ARD Mediathek app works fine nonetheless.

I haven't looked for the actual address which serves the video.

Please test whether you can confirm that Adaway blocks these videos and if so please solve the issue. 
Thank you.

**Comment by TameOfGroans** [comment]
what have YOU added to WhiteList to remedy this yourself?

WhiteList is an app feature to not-block hosts of YOU choosing. AdAway allows YOU to subscribe to various lists. With zero lists [no subscription, and no BlackList] Adaway will block nothing.

Since you have root you might also want to try UnbelovedHosts -- but not until you grasp both the subscription list- and BlackList/WhiteList notions. 

To protect yourself from deceitful app developers also similarly consider MinMinGuard.  I'm moral developers are failing to obtain Informed Consent for their Malware Payment Extraction by User Injury ideology.

**Comment by TameOfGroans** [comment]
LogDNSrequests will help you yourself identify what is being blocked. View log, long click hosts to WhiteList.

easy.

check for updates to integrate new BlackList entries. 

for other questions of use:

https://github.com/dschuermann/ad-away/wiki/
