### ISSUE TITLE
Adaway prevents the Disney Movies Anywhere app from playing movies

### ISSUE THREAD

**Issue by lallaria** [sufficientlysecure/ad-away#582]
I unfortunately can't really debug this (presumably it's a disney/go.com adserver that is being blocked), but I can say that with adaway disabled, it still doesn't show me any ads before playing a movie, so the movies themselves may be on the blocked server.

**Comment by TameOfGroans** [comment]
WhiteList is an app feature to not-block hosts of YOU choosing. AdAway allows YOU to subscribe to various lists. With zero lists [no subscription, and no BlackList] Adaway will block nothing.

LogDNSrequests will help you yourself identify what is being blocked. View log, long click hosts to WhiteList. easy.

Since you have root you might also want to try UnbelovedHosts -- but not until you grasp both the subscription list- and BlackList/WhiteList notions. 

To protect yourself from deceitful app developers also similarly consider MinMinGuard.  I'm moral developers are failing to obtain Informed Consent for their Malware Payment Extraction by User Injury ideology.

**Comment by TameOfGroans** [comment]
LogDNSrequests will help you yourself identify what is being blocked. View log, long click hosts to WhiteList.

easy.

check for updates to integrate new BlackList entries. 

for other questions of use:

https://github.com/dschuermann/ad-away/wiki/
