### ISSUE TITLE
"Never reboot" checkbox should disable the "Yes" option in the reboot prompt

### ISSUE THREAD

**Issue by stuartpb** [sufficientlysecure/ad-away#620]
It's kind of weird that I can tell AdAway that I never want to reboot, then have it reboot anyway.

**Comment by 0-kaladin** [comment]
I could "fix" this but I like this functionality.  I get this popup on fresh install of adaway.  for all future updates to hosts files i don't want it to reboot my phone I'd prefer to do it when i want.  But since this is my first application of the host file I like saying, I never want to reboot in the future but yes go ahead and reboot now so that I get that initial protection.  
So the checkbox says what do you want to do moving forward while the yes and no are what do you want to do now?  So typically i'll check the box but hit yes to get the first application of the hosts file applied.
