### ISSUE TITLE
PushBullet

### ISSUE THREAD

**Issue by mennoniteminuterice** [sufficientlysecure/ad-away#641]
When AdAway is running PushBullet does not automatically download files sent to it. With AdAway turned off this is not an issue. Please help! Thank you!

**Comment by 0-kaladin** [comment]
Please follow, https://github.com/sufficientlysecure/ad-away/wiki/BlockNewAds but instead of adding what you find to the blacklist, you will want to allow it so add to the whitelist.  This is not an AdAway issue but rather the nature of the hosts sources blocking something PushBullet is trying to connect to.  You simply need to find that something via the steps above and whitelist it.
